### ISSUE TITLE
Roadmap to first release

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/tapatalk-client-api#1]
- [x] Implement full api (without moderation, conversation, pms, attachments, avatar)
- [ ] Add possible exception throwings to phpdoc
- [ ] Test coverage
- [ ] Complete config mapping
- [ ] Add config assertion where possible
- [ ] Basic docs
